
```{r}

library(duckdb)
library(DBI)
library(dplyr)
library(tibble)
library(ggplot2)
DB_PATH = '../data/tcga_brca.duckdb'
con <- dbConnect(duckdb(), dbdir = DB_PATH, read_only = TRUE)

# browse tables
dbListTables(con)

# quick looks
clinical <- dbGetQuery(con, "SELECT * FROM staging.clinical") %>% tibble()

mutations <- dbGetQuery(con, "SELECT * FROM staging.mutations") %>% tibble()

marts_survival <- dbGetQuery(con, "SELECT * FROM marts.survival") %>% tibble()

dbGetQuery(con, "SELECT * FROM raw.maf LIMIT 5")
dbGetQuery(con, "SELECT * FROM raw.rna_expression LIMIT 5")

```



```{r}
clinical %>% ggplot(aes(x = overall_survival_days, fill = 'salmon')) + geom_histogram() + theme_bw()
```



```{r}
library(maftools)

maf_data <- dbGetQuery(con, "SELECT * FROM raw.maf")

maf <- read.maf(maf = maf_data)

plotmafSummary(maf, rmOutlier = TRUE, addStat = 'median')
oncoplot(maf = maf, top = 20)
```

```{r}
library(survival)
library(survminer)
fit <- survfit(
    Surv(overall_survival_days, vital_status) ~ stage_group,
    data = patient_summary %>% 
        filter(stage_group %in% c("I", "II", "III", "IV"))
)

ggsurvplot(
    fit,
    data = patient_summary,
    pval = TRUE,
    legend.title = "Stage",
    legend.labs = c("I", "II", "III", "IV"),
    xlab = "Days",
    ylab = "Survival Probability"
)
```


# cox

```{r}
cox <- coxph(
    Surv(overall_survival_days, vital_status) ~ 
        stage_group + age_at_diagnosis_years + tmb,
    data = patient_summary
)
summary(cox)
```



```{r}
# get top mutated genes per patient as binary flags
gene_matrix <- dbGetQuery(con, "
    SELECT 
        patient_id,
        MAX(CASE WHEN gene_symbol = 'TP53'   THEN 1 ELSE 0 END) as tp53,
        MAX(CASE WHEN gene_symbol = 'PIK3CA' THEN 1 ELSE 0 END) as pik3ca,
        MAX(CASE WHEN gene_symbol = 'CDH1'   THEN 1 ELSE 0 END) as cdh1,
        MAX(CASE WHEN gene_symbol = 'GATA3'  THEN 1 ELSE 0 END) as gata3,
        MAX(CASE WHEN gene_symbol = 'MAP3K1' THEN 1 ELSE 0 END) as map3k1,
        MAX(CASE WHEN gene_symbol = 'PTEN'   THEN 1 ELSE 0 END) as pten
    FROM staging.mutations
    GROUP BY patient_id
")

survival_genes <- patient_summary %>%
    left_join(gene_matrix, by = "patient_id") %>%
    filter(stage_group %in% c('I','II','III','IV'))

cox_genes <- coxph(
    Surv(overall_survival_days, vital_status) ~ 
        stage_group + age_at_diagnosis_years + tp53 + pik3ca + cdh1 + gata3 + map3k1 + pten,
    data = survival_genes
)

summary(cox_genes)
survival_genes <- survival_genes %>%
    mutate(stage_group = factor(stage_group, levels = c("I", "II", "III", "IV")))

library(broom)

tidy(cox_genes, exponentiate = TRUE, conf.int = TRUE) %>%
    filter(!grepl("stage|age", term)) %>%
    ggplot(aes(x = estimate, y = term, xmin = conf.low, xmax = conf.high)) +
    geom_pointrange() +
    geom_vline(xintercept = 1, linetype = "dashed", color = "red") +
    labs(x = "Hazard Ratio", y = NULL, title = "Gene mutation effect on survival\n(adjusted for stage and age)") +
    theme_minimal()

```


# rna vs dna

```{r}

```


```{r}
patient_summary %>%
    arrange(tmb_group, overall_survival_days) %>%
    mutate(patient_id = fct_inorder(patient_id)) %>%
    ggplot(aes(x = overall_survival_days, y = patient_id, fill = factor(vital_status))) +
    geom_col() +
    facet_wrap(~ tmb_group, scales = "free_y", ncol = 1) +
    scale_fill_manual(
        values = c("0" = "steelblue", "1" = "firebrick"),
        labels = c("0" = "Alive", "1" = "Deceased")
    ) +
    labs(
        x = "Overall Survival (days)",
        y = NULL,
        fill = "Status"
    ) +
    theme_minimal() +
    theme(axis.text.y = element_blank())
```



```{r}
library(forcats)
patient_summary %>%
    arrange(tmb_group, overall_survival_days) %>%
    mutate(patient_id = fct_inorder(patient_id)) %>%
    ggplot(aes(x = overall_survival_days, y = patient_id, fill = factor(vital_status))) +
    geom_col() +
    facet_wrap(~ tmb_group, scales = "free_y", ncol = 1) +
    scale_fill_manual(
        values = c("0" = "steelblue", "1" = "firebrick"),
        labels = c("0" = "Alive", "1" = "Deceased")
    ) +
    labs(
        x = "Overall Survival (days)",
        y = NULL,
        fill = "Status"
    ) +
    theme_minimal() +
    theme(axis.text.y = element_blank())
```